version: "3.2"
services:
  satis:
    image: ypereirareis/docker-satis:${IMAGE_VERSION:-3.4.0-debian-bullseye-php81-composer2}
    build: ./
    container_name: satis
    hostname: satis
    networks:
      - webproxy
    volumes:
      - "/var/tmp/composer:/var/www/.composer"
      - "~/.ssh/id_rsa:/var/tmp/id"
      - "./config:/satisfy/config_tmp"
    environment:
      PRIVATE_REPO_DOMAIN_LIST: bitbucket.org gitlab.com github.com
      CRONTAB_FREQUENCY: "*/1 * * * *"
      VIRTUAL_HOST: ${VHOST}

networks:
  webproxy:
    external:
      name: ${PROXY_NETWORK}
