satis:
    image: ypereirareis/docker-satis:3.0
    hostname: satis
    volumes:
        - "/var/tmp/composer:/root/.composer"
        - "~/.ssh/id_rsa:/var/tmp/id"

    environment:
        PRIVATE_REPO_DOMAIN_LIST: bitbucket.org gitlab.com github.com
        CRONTAB_FREQUENCY: "*/1 * * * *"
        VIRTUAL_HOST: satis.localhost
    ports:
        - 3000:3000
        - 80:80
